### ISSUE TITLE
[Suggestion] Lobby Stats

### ISSUE THREAD

**Issue by DrakusorU** [timche/faceit-enhancer#2]
Hey, about the new update and the player stats.. personally I like it more like this https://prnt.sc/iqvmb1 it just looks a lot cleaner and elegant for me.. the photo above its faceit helper modified..

My suggestion is to move the stats below the grey bar like in the photo, don't make it a tabel like that, it just feels like it occupies a lot of space when it could be more compact ( i see you tried to make it compact by making the text smaller.. if you do it like in the photo above you can make the text bigger, so easier to read, occupying the same space ).. You should move the elo down with the stats.. I would like it if you don't remove the nickname to show the elo.. when people changes their nickname that was a way to know who they are as that is their steam nickname.. The teams AVG. ELO looks nice like that below the teams name and I don't really see the point of showing the total elo, the avg. elo should be enough as only the difference between the average matters in how much elo you lose or win.

Also the stats, you should probably show the average headshot instead of winrate so we have the total matches and the avg headshot, avg kills, avg k/d, avg k/r in the last X games..

Also I feel like it looks better with the country flag next to the level and the icon bigger, you can also use https://cdn.faceit.com/frontend/291/assets/images/flags/  291 or 597 ( 597 is used by faceit on the profiles, leaderboards, rankings etc ) instead of the 561 you use now

**Comment by timche** [comment]
Thanks for your feedback.

![](https://i.imgur.com/t8QYtK5.png)

As you can see in the picture above, they both take the same amount of space for the stats. As you said, that is your personal opinion. The goal of the stats table and overall appearance was it to look like a part of the FACEIT website design, whereas I can't see it in the FACEIT HELPER example. Also the white text makes too prominent.

The Elo isn't part of the stats because it's not any extra stat that I would consider part of it, so it's under the nickname as the player stats can also be enabled/disabled.

I see your point regarding the Steam nickname, but how many times does it happen that it would justify to not replace it? You still have the option to click on the Steam icon to go to their Steam profile to look it up for this. 

Some were requesting avg. and total team Elo, so I can't satisfy everyone by saying I remove it again because someone was saying he doesn't need it and vice versa. I might consider to make it configurable instead. Same goes for what stats to show.

Regarding the flags it's totally personal preference. The numbers are indicating the website version and there is no difference between 597 and 561. So 291 are just the assets from the old website. The reason for choosing 561/597 was to adapt to the current FACEIT website design, so it matches the overall appearance.
